name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Code Static Analysis with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Unit Tests & Code Coverage
        run: |
          pip install coverage
          coverage run -m unittest discover -s backend -p "test_*.py"
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          
      - name: Check Chrome Version
        run: |
          google-chrome --version
          which chromedriver
      
      - name: Start Frontend
        run: |
          cd frontend
          nohup npm run serve &
          sleep 5 
        env:
          CI: true

      - name: Deploy Backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/srv-d07a8nili9vc73f4e9ng/deploys

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy Frontend to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
          VUE_APP_AT_URL: ${{ secrets.VUE_APP_AT_URL }}
        run: |
          cd frontend
          npm run build
          netlify deploy --dir=dist --prod --site=$NETLIFY_SITE_ID